version: "3"

services:
    webserver:
        image: nginx:latest
        ports:
            - "8021:80"
        volumes:
            - ./:/opt/app
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
        - php
    php:
        image: php:7-fpm
        volumes:
            - ./:/opt/app
    db:
        image: mysql/mysql-server:5.6
        volumes:
            - "./ops/docker/mysql/raw:/var/lib/mysql"
            - "./ops/docker/mysql/conf/my.cnf:/etc/my.cnf"
        environment:
            - "MYSQL_DATABASE=docker_test"
            - "MYSQL_ROOT_PASSWORD=password"
            - "MYSQL_ROOT_HOST=%"
        ports:
            - "33063:3306"
